INSERT INTO `ORDER` (`ID`, `SHIPPING_ADDRESS`) VALUES(1, 'Seoul');
INSERT INTO `ORDER` (`ID`, `SHIPPING_ADDRESS`) VALUES(2, 'Pusan');
INSERT INTO `ORDER` (`ID`, `SHIPPING_ADDRESS`) VALUES(3, 'Inchon');